version: "3.8"
services:
  c-bakend:
    container_name: c-bakend
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - .:/app
    working_dir: /app/server
    ports:
      - "${APP_PORT}:1222"
    restart: always
    tty: true
    command: sh ./scripts/api.sh
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - c_network

  mysql:
    container_name: mysql
    platform: linux/amd64
    image: "mysql:8.0"
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - "mysql-db:/var/lib/mysql"
      - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
    networks:
      - c_network
    command: mysqld --innodb_use_native_aio=0

  setup:
    container_name: setup
    image: alpine:latest
    volumes:
      - .:/app
    working_dir: /app
    command: cp pre-commit .git/hooks/pre-commit

volumes:
  mysql-db:
    driver: local

networks:
  c_network:
    external: true
